### PR TITLE
Feature: Page Navigation Implemented

### LINKED ISSUE #4: Page Navigation
As a user, I want to be able to navigate to different pages (like pantry or search) from any page so I can quickly get to pages I want.

Acceptance criteria:
- Has links to Home, Registration, Food Search, Pantry
- Links correctly direct to respective pages
- Navigation is show on every page

Tasks:
- Build proper page routing - 6 pages
- Title on each page to clearly display which frame is which 
- Navigation bar on each page (footer) to quickly click to each page

### PR DESCRIPTION
**Pull request by jjjjess**
- Routing completed for 6 pages: Home, Login, Register, Food-Search, Pantry, Some-Recipe
- Each page includes a header to show which page is which
- Footer with links to quickly navigate through application
- CSS added to make it easier on the eyes (dark mode)

### CODE REVIEW

**Comment by mhenning3** [comment]
reviewed and approved

**Review by mhenning3 — COMMENTED** [review]
Fixed it, looks good

**Review by amoots-emich — APPROVED** [review]
Looks good. Not sure we can get around the size of package-lock.json.

**Comment by amoots-emich** [comment]
I'll deploy to production for final testing.

**Comment by amoots-emich** [comment]
I have tested this successfully on the production server. It meets all the acceptance criteria in issue #4 so I will complete this request.

**Pull request merged**
